services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - open_library_network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack_container
    ports:
      - "6379:6379"
      - "8001:8001"
    networks: 
      - open_library_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_container
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - open_library_network

  

volumes:
  mongo_data:
networks:
  open_library_network:
